#!/bin/bash
#SBATCH --job-name=data_organize
#SBATCH --partition=savio2_bigmem
#SBATCH --time=3-00:00:00
#SBATCH --nodes=1
module load java

source /global/scratch/lucy3_li/anaconda3/bin/activate /global/scratch/lucy3_li/anaconda3/envs/nlp

time /global/home/users/lucy3_li/spark-2.4.4-bin-hadoop2.7/bin/spark-submit --master 'local[*]' --executor-memory 64G --driver-memory 64G --conf "spark.driver.extraJavaOptions=-Djava.io.tmpdir=/global/scratch/lucy3_li" /global/scratch/lucy3_li/ingroup_lang/code/data_organize.py

source /global/scratch/lucy3_li/anaconda3/bin/deactivate

